Flights/Controllers/FlightController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Flights.Models;
using Flights.DAL.Service.Interfaces;

namespace Flights.Controllers
{
    public class FlightController : Controller
    {
        private readonly ILogger<FlightController> _logger;
        private readonly IFlightService _flightService;
        private readonly IAirportService _airportService;

        /// <summary>
        /// Constructor injects all dependencies
        /// </summary>
        /// <param name="logger">ILogger Interface for logging purposes</param>
        /// <param name="FlightService">Interface for Flight Service (Service-Repository Pattern)</param>
        /// <param name="AirportService">Interface for Airport Service (Service-Repository Pattern)</param>
        public FlightController(ILogger<FlightController> logger,
                                IFlightService FlightService,
                                IAirportService AirportService)
        {
            _airportService = AirportService;
            _flightService = FlightService;
            _logger = logger;
        }

        public IActionResult Index()
        {
            var model = _flightService.GetAll();
            return View(model);
        }

        public IActionResult Create()
        {
            return View();
        }
        
        [HttpGet]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flightViewModel = await _flightService.GetById(id.Value);

            if (flightViewModel == null)
            {
                return NotFound();
            }

            return View(flightViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(FlightViewModel flight)
        {
            _logger.LogInformation(flight.ToString());
            var result = _flightService.Create(flight);
            if (result.Result.Status)
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Error");
        }

        public IActionResult GetAllAirports()
        {
            try
            {
                var airports = _airportService.GetAll();
                if (!airports.Any())
                {
                    return NotFound();
                }
                return Ok(airports);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message, "Failed to retrieve airports");
                return BadRequest("Failed to retrieve airports");
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(FlightViewModel flight)
        {
            if (!ModelState.IsValid) return View(flight);

            var result = _flightService.Update(flight);
            if (result.Result.Status)
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Error");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Flights/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Flights.Models;
using Flights.DAL.Service.Interfaces;

namespace Flights.Controllers
{
    public class ReportController : Controller
    {
        private readonly IReportService _reportService;
        
        /// <summary>
        /// Constructor injects all dependencies
        /// </summary>
        /// <param name="ReportService">Interface for Report Service (Service-Repository Pattern)</param>
        public ReportController(IReportService reportService)
        {
            _reportService = reportService;
        }

        public IActionResult Index()
        {
            var model = _reportService.GetAll();
            return View(model);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Flights/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Flights</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.11/css/bootstrap-select.css" integrity="sha256-aPRK3MQ0gmmxF1ovonFB/U1mCdRHB8q9+99WqHvuXTk=" crossorigin="anonymous" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Flight" asp-action="Index">Flights</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Report" asp-action="Index">Reports</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Flights - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.11/js/bootstrap-select.js" integrity="sha256-39+tYK5vTA0PP3DneltYgkUUn5cjBzO+QfduyEA5rRQ=" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>